version: '3.4'

services:
  db:
    image: postgres:13.4
    restart: always
    env_file:
      - ./docker/env.db
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - ./.env
      - ./docker/env.db
    container_name: saas-erp
    command: ./docker/scripts/run-gunicorn
    volumes:
      - static_volume:/opt/code/static
      - media_volume:/opt/code/media
      - shm:/dev/shm
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
      dockerfile: staging.Dockerfile
    restart: always
    ports:
      - 8002:80
    volumes:
      - static_volume:/opt/code/static
      - media_volume:/opt/code/media
      - shm:/dev/shm
    depends_on:
      - app

volumes:
  db_data:
  static_volume:
  media_volume:
  shm:
