# Generated by Django 4.0.5 on 2022-06-27 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=20)),
                ('nic', models.CharField(max_length=25)),
                ('date_of_joining', models.DateField()),
                ('emergency_contact_number', models.CharField(max_length=20)),
                ('last_employer_experience_letter', models.BooleanField(default=False)),
                ('last_employer_salary_slip', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Salaries',
            },
        ),
        migrations.CreateModel(
            name='Degrees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programe', models.CharField(max_length=50)),
                ('institute', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=4)),
                ('year_of_graduation', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degrees', to='core.employee')),
            ],
        ),
    ]
