# Generated by Django 4.0.5 on 2022-07-20 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_asset_assettype_benefit_compensation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compensation',
            name='hourly_limit_per_month',
        ),
        migrations.RemoveField(
            model_name='compensation',
            name='hourly_limit_per_week',
        ),
        migrations.AddField(
            model_name='compensation',
            name='expected_hours_per_week',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='compensation',
            name='max_hours_per_week',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.documenttype'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('tax', models.FloatField()),
                ('currency_convesion_rates', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.currency')),
            ],
        ),
        migrations.AddField(
            model_name='compensationhistory',
            name='payroll',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.payroll'),
            preserve_default=False,
        ),
    ]
