# Generated by Django 4.0.5 on 2022-07-22 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_remove_compensation_hourly_limit_per_month_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="is_owner",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="app.role"
            ),
        ),
        migrations.AlterField(
            model_name="compensationhistory",
            name="payroll",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="app.payroll"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="app.documenttype",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="app.employmenttype",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="organization",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.organization",
            ),
        ),
    ]
