# Generated by Django 4.0.5 on 2022-07-22 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_compensation_hourly_limit_per_month_and_more'),
        ('app', '0007_alter_user_organization'),
    ]

    operations = [
    ]
