# Generated by Django 4.0.5 on 2022-07-23 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_remove_user_role_role_is_member_usermodulerole"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="default_role",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="app.role"
            ),
        ),
    ]
