# Generated by Django 4.0.5 on 2022-07-23 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_user_default_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="default_role",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="app.role"
            ),
        ),
    ]
