# Generated by Django 4.0.5 on 2022-07-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_role_is_default_alter_user_default_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
