# Generated by Django 4.0.5 on 2022-07-26 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_user_is_onboarded_invitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='role',
            name='is_member',
        ),
        migrations.RemoveField(
            model_name='role',
            name='is_owner',
        ),
        migrations.AddField(
            model_name='role',
            name='permission',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=10),
        ),
        migrations.AlterField(
            model_name='usermodulerole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_roles', to=settings.AUTH_USER_MODEL),
        ),
    ]
