# Generated by Django 4.0.6 on 2022-07-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_module_is_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="permission",
            field=models.CharField(
                choices=[("c", "Owner"), ("b", "Admin"), ("a", "Member")],
                default="a",
                max_length=1,
            ),
        ),
    ]
