# Generated by Django 4.0.6 on 2022-07-31 06:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_alter_role_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="compensation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="organizationmodule",
            constraint=models.UniqueConstraint(
                fields=("module", "organization"),
                name="organization_module_constrataint",
            ),
        ),
    ]
