# Generated by Django 4.0.6 on 2022-08-04 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_employee_designation_employee_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={"ordering": ["-id"]},
        ),
        migrations.RemoveField(
            model_name="employee",
            name="email",
        ),
    ]
