# Generated by Django 4.0.6 on 2022-08-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_employee_designation_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
