# Generated by Django 4.1 on 2022-08-10 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_alter_module_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="name",
        ),
        migrations.AddField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="user_allowed",
            field=models.BooleanField(default=False),
        ),
    ]
