# Generated by Django 4.1.1 on 2022-09-24 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_remove_employee_name_employee_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="organization",
        ),
    ]
