# Generated by Django 4.1.3 on 2022-11-24 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0028_company_alter_employee_nic_experience"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={},
        ),
    ]
