# Generated by Django 4.1.3 on 2022-11-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_company_alter_employee_nic_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='benefits',
            field=models.ManyToManyField(blank=True, to='app.benefit'),
        ),
    ]
