# Generated by Django 4.1 on 2022-12-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0030_remove_employee_contact_number_user_contact_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="slack_id",
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
