# Generated by Django 4.1 on 2022-12-06 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0031_company_image_currency_organization_institute_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="slack_id",
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_in", models.DateTimeField(auto_now_add=True)),
                ("time_out", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.employee"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.organization",
                    ),
                ),
            ],
        ),
    ]
