# Generated by Django 4.1 on 2022-12-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0032_attendance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="time_out",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
