# Generated by Django 4.1.3 on 2022-12-12 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0033_employee_salary_alter_asset_employee"),
    ]

    operations = [
        migrations.CreateModel(
            name="Standup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("standup_time", models.DateTimeField(auto_now_add=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.team"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StandupUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("update_time", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(max_length=50)),
                ("work_done_yesterday", models.TextField()),
                ("work_to_do", models.TextField()),
                ("blockers", models.TextField()),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.employee"
                    ),
                ),
                (
                    "standup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.standup"
                    ),
                ),
            ],
        ),
    ]
