# Generated by Django 4.1 on 2022-12-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0033_employee_salary_alter_asset_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="institute",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.URLField(
                default="https://prixite-erp-dev.s3.ap-southeast-1.amazonaws.com/media/bpD666m3TGWrvp75gU8nhh.png"  # noqa
            ),
        ),
    ]
