# Generated by Django 4.1.3 on 2022-12-19 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='hr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaves_hr', to='app.employee'),
        ),
    ]
