# Generated by Django 4.1.3 on 2022-12-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_leave_hr'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='leave_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
