# Generated by Django 4.1.3 on 2022-12-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0040_leave_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="leave",
            name="hr_comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
