# Generated by Django 4.1 on 2023-01-03 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0041_leave_description_leave_hr_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leave",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="managed_leaves",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
