# Generated by Django 4.1 on 2023-01-04 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0042_alter_leave_updated_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={"ordering": ["id"]},
        ),
    ]
