# Generated by Django 4.1 on 2023-01-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0043_alter_employee_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="contact_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="headline",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="headline"
            ),
        ),
    ]
