# Generated by Django 4.1 on 2023-01-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0044_alter_user_contact_number_alter_user_headline"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="leave_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sick leave", "Sick Leave"),
                    ("annual leave", "Annual Leave"),
                    ("casual leave", "Casual Leave"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="leave",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("denied", "Denied"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
