# Generated by Django 4.1.3 on 2023-01-12 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0044_alter_user_contact_number_alter_user_headline"),
    ]

    operations = [
        migrations.CreateModel(
            name="Standup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField()),
                (
                    "team",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="app.team"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StandupUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("missed", "Missed"),
                            ("joined", "Joined"),
                            ("leave", "Leave"),
                        ],
                        max_length=10,
                    ),
                ),
                ("work_done_yesterday", models.TextField(blank=True, null=True)),
                ("work_to_do", models.TextField(blank=True, null=True)),
                ("blockers", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.employee"
                    ),
                ),
                (
                    "standup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.standup"
                    ),
                ),
            ],
        ),
    ]
