# Generated by Django 4.1.5 on 2023-01-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0045_leave_leave_type_alter_leave_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bill_update_email",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="bill_update_phone",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="new_team_member_email",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="new_team_member_phone",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="newsletters_email",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="newsletters_phone",
            field=models.BooleanField(default=False),
        ),
    ]
