# Generated by Django 4.1.5 on 2023-01-17 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0045_standup_standupupdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="standup",
            name="name",
            field=models.CharField(default="name", max_length=128),
        ),
        migrations.AddField(
            model_name="standup",
            name="organization",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.organization",
            ),
        ),
        migrations.AddField(
            model_name="standupupdate",
            name="organization",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.organization",
            ),
        ),
    ]
