# Generated by Django 4.1.5 on 2023-01-17 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0046_standup_name_standup_organization_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standup",
            name="name",
            field=models.CharField(max_length=128, unique="True"),
        ),
        migrations.AlterField(
            model_name="standup",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.organization"
            ),
        ),
        migrations.AlterField(
            model_name="standupupdate",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.organization"
            ),
        ),
    ]
