# Generated by Django 4.1.5 on 2023-01-17 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0045_leave_leave_type_alter_leave_status"),
        ("app", "0047_alter_standup_name_alter_standup_organization_and_more"),
    ]

    operations = []
