# Generated by Django 4.1.5 on 2023-01-18 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0046_user_bill_update_email_user_bill_update_phone_and_more"),
        ("app", "0048_merge_20230117_0937"),
    ]

    operations = []
