# Generated by Django 4.1 on 2023-01-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0049_merge_20230118_1050"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="email address"),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                fields=("email", "organization"), name="unique_organization_user"
            ),
        ),
    ]
