# Generated by Django 4.1 on 2023-02-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0051_employee_is_deleted_user_is_deleted_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="availability_end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="availability_last_msg",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="availability_start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="monthly_available_hours",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="weekly_available_hours",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
