# Generated by Django 4.1.5 on 2023-01-31 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0052_alter_module_name"),
    ]

    operations = []
