# Generated by Django 4.1 on 2023-02-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0052_employee_availability_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="slug",
            field=models.SlugField(
                choices=[
                    ("payroll", "Payroll"),
                    ("user", "User"),
                    ("employees", "Employees"),
                    ("inventory", "Inventory"),
                    ("settings", "Settings"),
                    ("availability_messages", "Availability_Messages"),
                ]
            ),
        ),
    ]
