# Generated by Django 4.1.5 on 2023-01-31 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0053_merge_20230131_1745"),
    ]

    operations = [
        migrations.AddField(
            model_name="standup",
            name="time",
            field=models.TimeField(
                default=datetime.datetime(
                    2023, 1, 31, 6, 45, 34, 807630, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="standup",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="standup",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
