# Generated by Django 4.1 on 2023-02-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0055_alter_team_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="slug",
            field=models.SlugField(
                choices=[
                    ("payroll", "Payroll"),
                    ("user", "User"),
                    ("employees", "Employees"),
                    ("inventory", "Inventory"),
                    ("settings", "Settings"),
                    ("leave", "Leave"),
                    ("standup", "Standup"),
                ]
            ),
        ),
    ]
