# Generated by Django 4.1.5 on 2023-02-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0056_alter_module_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="slug",
            field=models.SlugField(
                choices=[
                    ("payroll", "Payroll"),
                    ("user", "User"),
                    ("employees", "Employees"),
                    ("inventory", "Inventory"),
                    ("settings", "Settings"),
                    ("leave", "Leave"),
                    ("standup", "Standup"),
                ],
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="standup",
            name="name",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=128),
        ),
    ]
