# Generated by Django 4.1.5 on 2023-02-10 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0057_alter_module_slug_alter_standup_name_alter_team_name"),
        ("app", "0057_alter_team_members"),
    ]

    operations = []
