# Generated by Django 4.1 on 2023-02-13 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0053_alter_module_slug"),
        ("app", "0058_merge_20230210_1126"),
    ]

    operations = []
