# Generated by Django 4.1.5 on 2023-02-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0061_alter_module_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="availability_end_time",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="availability_last_msg",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="availability_start_time",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="monthly_available_hours",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="weekly_available_hours",
        ),
        migrations.AlterField(
            model_name="module",
            name="slug",
            field=models.SlugField(
                choices=[
                    ("payroll", "Payroll"),
                    ("user", "User"),
                    ("employees", "Employees"),
                    ("inventory", "Inventory"),
                    ("settings", "Settings"),
                    ("leave", "Leave"),
                    ("standup", "Standup"),
                ],
                unique=True,
            ),
        ),
    ]
