# Generated by Django 4.1.5 on 2023-02-21 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0057_notification"),
        ("app", "0061_alter_module_slug"),
    ]

    operations = []
