# Generated by Django 4.1.7 on 2023-02-27 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0062_employee_currency_alter_currency_symbol"),
        ("app", "0062_merge_0057_notification_0061_alter_module_slug"),
    ]

    operations = []
