# Generated by Django 4.1.7 on 2023-02-27 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0062_folder_documents"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("document_url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.employee"
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app.documenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="document",
            name="document_url",
        ),
        migrations.RemoveField(
            model_name="document",
            name="employee",
        ),
        migrations.RemoveField(
            model_name="document",
            name="name",
        ),
        migrations.RemoveField(
            model_name="document",
            name="type",
        ),
        migrations.AddField(
            model_name="document",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="document_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="folder",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="app.folder",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="text",
            field=models.TextField(default=2008),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="document",
            name="title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.DeleteModel(
            name="Documents",
        ),
    ]
