# Generated by Django 4.1.5 on 2023-03-01 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0063_availability"),
        ("app", "0063_folder_remove_document_document_url_and_more"),
    ]

    operations = []
