# Generated by Django 4.1.7 on 2023-04-04 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0065_payroll_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payroll",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.employee"
            ),
        ),
    ]
